"use client"; // Required for Next.js 13+ App Router

import { useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { animate, scroll } from "motion";

export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined") {
      // Progress bar animation
      const progressBar = document.querySelector(".progress");
      if (progressBar) {
        scroll(animate(progressBar, { scaleX: [0, 1] }, { ease: "linear" }));
      }

      // Apply scroll animations to all section headers
      document.querySelectorAll(".img-container").forEach((section) => {
        const header = section.querySelector("h2");
        if (header) {
          scroll(
            animate(header, { y: [-100, 100], opacity: [0, 1] }, { duration: 0.5 }),
            { target: section }
          );
        }
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/motion/dist/motion.umd.min.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          {/* Scroll Snapping Image Sections */}
          <div className={styles.gallery}>
            {[...Array(5)].map((_, index) => (
              <section className="img-container" key={index}>
                <div>
                  <img src="/images/suki.png" alt={`Project ${index + 1}`} />
                  <h2>#{String(index + 1).padStart(3, "0")}</h2>
                </div>
              </section>
            ))}
          </div>

          {/* Scroll Progress Bar */}
          <div className="progress"></div>
        </main>
      </div>

      <Footer />
    </>
  );
}
