"use client"; 

import { useEffect, useRef } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { animate, scroll } from "motion";

const imageList = [
  "/images/suki.png",
  "/images/suki.png",
  "/images/suki.png",
  "/images/suki.png",
  "/images/suki.png"
];

export default function Home() {
  const progressRef = useRef(null);
  const galleryRef = useRef(null);
  const sectionsRef = useRef([]);

  useEffect(() => {
    if (typeof window !== "undefined" && galleryRef.current) {
      // Animate progress bar during scroll
      if (progressRef.current) {
        scroll(
          animate(progressRef.current, { scaleX: [0, 1] }, { ease: "linear" }),
          { container: galleryRef.current }
        );
      }

      // Animate image numbers on scroll
      sectionsRef.current.forEach((section) => {
        const header = section?.querySelector("h2");
        if (header) {
          scroll(
            animate(header, { y: [-50, 0], opacity: [0, 1] }, { duration: 0.5 }),
            { target: section, container: galleryRef.current }
          );
        }
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1 className={styles.name}>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          {/* Scroll Snapping Image Sections */}
          <div
      className="gallery"
      ref={galleryRef}
      style={{ overflowY: "auto", height: "100vh" }} // Ensures scrolling works
    >
      {imageList.map((image, index) => (
        <section
          className="img-container"
          key={index}
          ref={(el) => (sectionsRef.current[index] = el)} // Attach ref dynamically
        >
          <div>
            <img src={image} alt={`Project ${index + 1}`} />
            <h2>#{String(index + 1).padStart(3, "0")}</h2>
          </div>
        </section>
      ))}

      {/* Scroll Progress Bar */}
      <div className="progress" ref={progressRef}></div>
    </div>
        </main>
      </div>

      <Footer />
    </>
  );
}
