import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { animate, scroll } from "motion";

export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined") {
      // Progress bar animation
      const progressBar = document.querySelector(".progress");
      if (progressBar) {
        scroll(animate(progressBar, { scaleX: [0, 1] }, { ease: "linear" }));
      }

      // Scrolling animation for headers
      document.querySelectorAll(".img-container").forEach((section) => {
        const header = section.querySelector("h2");
        if (header) {
          scroll(animate(header, { y: [-400, 400] }, { ease: "linear" }), {
            target: section,
          });
        }
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/motion/dist/motion.umd.min.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            {/* Full-width Banner Image */}
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />

            {/* Overlay Content */}
            <div className={styles.overlayContent}>
              <h1>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>

            {/* Logo Positioned on the Right */}
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          {/* Scroll Animation Sections */}
          <section className="img-container">
            <div>
              <img src="/images/suki.png" alt="Project 1" />
              <h2>#001</h2>
            </div>
          </section>
          <section className="img-container">
            <div>
              <img src="/images/suki.png" alt="Project 2" />
              <h2>#002</h2>
            </div>
          </section>
          <section className="img-container">
            <div>
              <img src="/images/suki.png" alt="Project 3" />
              <h2>#003</h2>
            </div>
          </section>
          <section className="img-container">
            <div>
              <img src="/images/suki.png" alt="Project 4" />
              <h2>#004</h2>
            </div>
          </section>
          <section className="img-container">
            <div>
              <img src="/images/suki.png" alt="Project 5" />
              <h2>#005</h2>
            </div>
          </section>

          {/* Progress Bar for Scroll Animation */}
          <div className="progress"></div>
        </main>
      </div>

      <Footer />
    </>
  );
}
