"use client"; 

import { scroll } from "motion"
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";



export default function Home() {
 


    // Progress bar representing gallery scroll
    scroll(animate(".progress", { scaleX: [0, 1] }, { ease: "linear" }))

    document.querySelectorAll(".img-container").forEach((section) => {
        const header = section.querySelector("h2")
        scroll(animate(header, { y: [-400, 400] }, { ease: "linear" }), {
            target: header,
        })
    })

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1 className={styles.name}>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          <section class="img-container">
    <div>
        <img src="/images/suki.png" />
        <h2>#001</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/images/suki.png" />
        <h2>#002</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/images/suki.png" />
        <h2>#003</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/images/suki.png" />
        <h2>#004</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/images/suki.png" />
        <h2>#005</h2>
    </div>
</section>
<div class="progress"></div>

          
        </main>
      </div>

      <Footer />
    </>
  );
}
