"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Link from "next/link";

export default function Home() {

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}

          <article className={styles.scroller}>
            <section>
              <div className={styles.bannerContainer}>
                <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
                <div className={styles.overlayContent}>
                  <h1 className={styles.name}>Madeline Struthers</h1>
                  <h2>Graphic & UX Designer</h2>
                </div>

              </div>
            </section>


            <section>
              <Link href="/projects/sqwell">
                <img src="/images/sqwell-home-page.jpg" alt="Sqwell Project" className={styles.posterImage} />
              </Link>
              <h2>Sqwell Web App</h2>
            </section>

            <section>
              <Link href="/projects/civica">
                <img src="/images/civica-home-page.jpg" alt="Civica Project" className={styles.posterImage} />
              </Link>
              <h2>Civica – Legal–aid Mobile App</h2>
            </section>

            <section>
              <Link href="/projects/viper-energy">
                <img src="/images/can.png" alt="Can Project" className={styles.posterImage} />
              </Link>
              <h2>Viper Energy Can Mockup</h2>
            </section>

            <section>
              <Link href="/projects/suki">
                <img src="/images/suki.png" alt="Suki Project" className={styles.posterImage} />
              </Link>
              <h2>Suki Waterhouse Poster</h2>
            </section>


            <section>
              <Link href="/projects/photoshop-painting">
                <img src="/images/opal-home-page.jpg" alt="Opal Halo Project" className={styles.posterImage} />
              </Link>
              <h2>Photoshop Painting</h2>
            </section>
          
          </article>
            <h3>Check out the rest of my projects!</h3>
        </main>
      </div>

      <Footer />
    </>
  );
}
