"use client"; 

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export default function Home() {

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1 className={styles.name}>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          <article class="scroller">
  <section>
  <img src="/images/suki.png" alt="poster" width={1000}  />
    <h2>Suki Waterhouse Poster</h2>
  </section>
  <section>
  <img src="/images/opal-halo.png" alt="poster" width={1000}  />
    <h2>Section two</h2>
  </section>
  <section>
    <h2>Section three</h2>
  </section>
</article>
        </main>
      </div>

      <Footer />
    </>
  );
}
