import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Madeline Struther's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div
        className={`${styles.page}`}
      >
       
        <main className={styles.main}>
        <div>
      <Image 
        src="/images/cover.png" 
        alt="Logo with watermark" 
        width={900} 
        height={415} 
        priority // Optional: improves performance for above-the-fold images
      />
    </div>
    
        </main>
       
      </div>
      <Footer/>
    </>
  );
}
