"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Link from "next/link";
import { useState, useEffect } from "react";
import WavyBanner from "@/components/WavyBanner";


export default function Home() {

  const [showScroll, setShowScroll] = useState(false);

  // Show button when scrolling down
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setShowScroll(true);
      } else {
        setShowScroll(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Scroll to top function
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}

         
            <section className={styles.scrollerBanner}>
          
              <div className={styles.bannerContainer}>
              <WavyBanner/>
               {/*  <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />*/}
                <div className={styles.overlayContent}>
                  <h1 className={styles.name}>Madeline Struthers</h1>
                  <h2 className={styles.jobTitle}>Graphic & UX Designer</h2>
                </div>

              </div>
            </section>

            <article className={styles.scroller}>
            <section className={styles.scrollerProjects} >
              <Link href="/projects/sqwell">
                <img src="/images/sqwell-home-page.jpg" alt="Sqwell Project" className={styles.posterImage} />
              </Link>
              <div className={styles.projectText}>
              <h2 className={styles.projectHeader}>Sqwell Web App</h2>
              <p>Interactive Web App for nature lovers</p>
              <h4 className={styles.link}> <a href="https://sqwell.vercel.app/">sqwell.vercel.app</a></h4>
              </div>
            </section>

            <section className={styles.scrollerProjects}>
              <Link href="/projects/civica">
                <img src="/images/project-card-civica.jpg" alt="Civica Project" className={styles.posterImage} />
              </Link>
              <div className={styles.projectText}>
              <h2 className={styles.projectHeader}>Civica – Legal Aid Mobile App</h2>
              <p>A legal support app designed to empower underprivileged women by providing accessible tools and guidance for navigating legal challenges.</p>
              <h4 className={styles.link}> <a href="https://www.civicalaw.ca/">civicalaw.ca</a></h4>
              </div>
            </section>

            <section className={styles.scrollerProjects}>
              <Link href="/projects/viper-energy">
                <img src="/images/can.png" alt="Can Project" className={styles.posterImage} />
              </Link>
              <div className={styles.projectText}>
              <h2 className={styles.projectHeader}>Viper Energy Can Mockup</h2>
              <p>The Viper Energy can design project involved creating three distinct designs for a fictional energy drink brand using Adobe Illustrator and Photoshop. </p>
              </div>
            </section>

            <section className={styles.scrollerProjects}>
              <Link href="/projects/suki">
                <img src="/images/suki.png" alt="Suki Project" className={styles.posterImage} />
              </Link>
              <div className={styles.projectText}>
              <h2 className={styles.projectHeader}>Suki Waterhouse Poster</h2>
              <p>Poster made in PhotoShop for the musical artist Suki</p>
              </div>
            </section>


            <section className={styles.scrollerProjects}>
              <Link href="/projects/photoshop-painting">
                <img src="/images/opal-home-page.jpg" alt="Opal Halo Project" className={styles.posterImage} />
              </Link>
              <div className={styles.projectText}>
              <h2 className={styles.projectHeader}>Photoshop Painting</h2>
              <p> A memorial painting of Opal the cat was created in Photoshop using a simple brush tool.</p>
              </div>
            </section>
            
          </article>
          {/*<section>
            <Link href="/projects">
            <h3>Check out the rest of my projects!</h3>
            </Link>
  </section>*/}
        </main>
      </div>


      { /* Back to Top Button }
       {showScroll && (
        <button onClick={scrollToTop} className={styles.scrollTop}>
          UP
        </button>
      )} */}
<Footer />


    </>
  );
}
