"use client";

import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Link from "next/link";

export default function Home() {
  const [showScroll, setShowScroll] = useState(false);
  const [disableSnap, setDisableSnap] = useState(false);

  // Show button when scrolling down
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setShowScroll(true);
      } else {
        setShowScroll(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Scroll to top function
  const scrollToTop = () => {
    setDisableSnap(true); // Temporarily disable snap scrolling
    window.scrollTo({ top: 0, behavior: "smooth" });

    // Re-enable snap scrolling after 1 second
    setTimeout(() => {
      setDisableSnap(false);
    }, 1000);
  };

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <article className={`${styles.scroller} ${disableSnap ? styles.noSnap : ""}`}>
            <section>
              <div className={styles.bannerContainer}>
                <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
                <div className={styles.overlayContent}>
                  <h1 className={styles.name}>Madeline Struthers</h1>
                  <h2>Graphic & UX Designer</h2>
                </div>
              </div>
            </section>

            {/* Project Sections */}
            {[
              { href: "/projects/sqwell", img: "sqwell-home-page.jpg", title: "Sqwell Web App", desc: "An innovative web app for music lovers." },
              { href: "/projects/civica", img: "civica-home-page.jpg", title: "Civica Legal App", desc: "A legal aid mobile app for accessibility." },
              { href: "/projects/viper-energy", img: "can.png", title: "Viper Energy Can Mockup", desc: "A sleek can design for an energy drink." },
              { href: "/projects/suki", img: "suki.png", title: "Suki Waterhouse Poster", desc: "A modern poster design for Suki Waterhouse." },
              { href: "/projects/photoshop-painting", img: "opal-home-page.jpg", title: "Photoshop Painting", desc: "A digital artwork using Photoshop." }
            ].map((project, index) => (
              <section key={index} className={styles.projectSection}>
                <Link href={project.href}>
                  <img src={`/images/${project.img}`} alt={project.title} className={styles.projectImage} />
                </Link>
                <div className={styles.projectDetails}>
                  <h2>{project.title}</h2>
                  <p>{project.desc}</p>
                </div>
              </section>
            ))}
          </article>

          <h3>Check out the rest of my projects!</h3>
        </main>
      </div>

      {/* Back to Top Button */}
      {showScroll && (
        <button onClick={scrollToTop} className={styles.scrollTop}>
          ↑
        </button>
      )}

      <Footer />
    </>
  );
}
