"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export default function Home() {

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}

          <article className={styles.scroller}>
  {/* Banner Section (Unchanged) */}
  <section>
    <div className={styles.bannerContainer}>
      <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
      <div className={styles.overlayContent}>
        <h1 className={styles.name}>Madeline Struthers</h1>
        <h2>Graphic & UX Designer</h2>
      </div>
    </div>
  </section>

   {/* Image Sections */}
   {["suki.png", "can.png", "opal-halo.jpg", "sqwell-cover.png"].map((img, index) => (
    <section key={index} className={styles.imageSection}>
      <div className={styles.imageWrapper}>
        <img src={`/images/${img}`} alt="poster" className={styles.animatedImage} />
      </div>
    </section>
  ))}
  
</article>


        </main>
      </div>

      <Footer />
    </>
  );
}
