"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export default function Home() {

  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}

          <article className={styles.scroller}>
          <section>
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1 className={styles.name}>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
           
          </div>
          </section>
          <div className={styles.posterImageContainer}>
          <section>
    <Link href="/projects/suki">
      <img src="/images/suki.png" alt="Suki Project" className={styles.posterImage}/>
    </Link>
    <h2>Suki Project</h2>
  </section>

  <section>
    <Link href="/projects/can">
      <img src="/images/can.png" alt="Can Project" className={styles.posterImage}/>
    </Link>
    <h2>Can Project</h2>
  </section>

  <section>
    <Link href="/projects/opal">
      <img src="/images/opal-home-page.jpg" alt="Opal Halo Project" className={styles.posterImage}/>
    </Link>
    <h2>Opal Halo Project</h2>
  </section>

  <section>
    <Link href="/projects/sqwell">
      <img src="/images/sqwell-home-page.jpg" alt="Sqwell Project" className={styles.posterImage}/>
    </Link>
    <h2>Sqwell Project</h2>
  </section>
            </div>
          </article>
        </main>
      </div>

      <Footer />
    </>
  );
}
