import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { animate, scroll } from "motion";

export default function Home() {

  const { animate, scroll } = window.Motion

    // Progress bar representing gallery scroll
    scroll(animate(".progress", { scaleX: [0, 1] }, { ease: "linear" }))

    document.querySelectorAll(".img-container").forEach((section) => {
        const header = section.querySelector("h2")
        scroll(animate(header, { y: [-400, 400] }, { ease: "linear" }), {
            target: header,
        })
    })


  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/motion/dist/motion.umd.min.js"></script>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div
        className={`${styles.page}`}
      >
       
        <main className={styles.main}>
        <div className={styles.bannerContainer}>
            {/* Full-width Banner Image */}
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />

            {/* Overlay Content */}
            <div className={styles.overlayContent}>
                <h1>Madeline Struthers</h1>
                <h2>Graphic & UX Designer</h2>
            </div>

            {/* Logo Positioned on the Right */}
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
        </div>

 {/* scroll animation */}
 
 <section class="img-container">
    <div>
        <img src="/photos/cityscape/1.jpg" />
        <h2>#001</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/photos/cityscape/2.jpg" />
        <h2>#002</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/photos/cityscape/3.jpg" />
        <h2>#003</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/photos/cityscape/4.jpg" />
        <h2>#004</h2>
    </div>
</section>
<section class="img-container">
    <div>
        <img src="/photos/cityscape/5.jpg" />
        <h2>#005</h2>
    </div>
</section>
<div class="progress"></div>


        </main>
       
      </div>
      <Footer/>
    </>
  );
}
