"use client"; // Required for Next.js 13+ App Router

import { useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { animate, scroll } from "motion";

const imageList = [
  "/images/image1.jpg",
  "/images/image2.jpg",
  "/images/image3.jpg",
  "/images/image4.jpg",
  "/images/image5.jpg"
];

export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined") {
      const progressBar = document.querySelector(".progress");

      if (progressBar) {
        scroll(animate(progressBar, { scaleX: [0, 1] }, { ease: "linear" }));
      }

      document.querySelectorAll(".img-container").forEach((section) => {
        const header = section.querySelector("h2");
        if (header) {
          scroll(
            animate(header, { y: [-50, 0], opacity: [0, 1] }, { duration: 0.5 }),
            { target: section }
          );
        }
      });
    }
  }, []);


  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className={styles.page}>
        <main className={styles.main}>
          {/* Banner Section */}
          <div className={styles.bannerContainer}>
            <img src="/images/full-width-banner.jpg" alt="Full Width Banner" className={styles.fullWidthImg} />
            <div className={styles.overlayContent}>
              <h1 className={styles.name}>Madeline Struthers</h1>
              <h2>Graphic & UX Designer</h2>
            </div>
            <img src="/images/ms-logo.svg" alt="MS Logo" className={styles.logo} />
          </div>

          {/* Scroll Snapping Image Sections */}
          <div className="gallery">
      {imageList.map((image, index) => (
        <section className="img-container" key={index}>
          <div>
            <img src={image} alt={`Project ${index + 1}`} />
            <h2>#{String(index + 1).padStart(3, "0")}</h2>
          </div>
        </section>
      ))}

      {/* Scroll Progress Bar */}
      <div className="progress"></div>
    </div>
        </main>
      </div>

      <Footer />
    </>
  );
}
