import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Madeline Struthers Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div
        className={`${styles.page}`}
      >
       
        <main className={styles.main}>
        <img src="/images/full-width-banner.png" alt="Full Width" className={styles.fullWidthImg} />

        </main>
       
      </div>
      <Footer/>
    </>
  );
}
